# Generated by Django 6.0.5 on 2026-05-13 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('allergies', models.TextField()),
                ('chronic_conditions', models.TextField()),
                ('emergency_contact', models.BigIntegerField()),
                ('insurance_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_provider.insuranceprovider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
