# Generated by Django 6.0.5 on 2026-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
