# Generated by Django 6.0.5 on 2026-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_email_otp',
            field=models.SmallIntegerField(null=True),
        ),
    ]
