# Generated by Django 6.0.5 on 2026-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_customuser_forgot_password_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='forgot_password_email_otp',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
