# Generated by Django 6.0.5 on 2026-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_phone_otp',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
