# Generated by Django 6.0.5 on 2026-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0005_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_account_verified',
            field=models.BooleanField(default=True),
        ),
    ]
