# Generated by Django 6.0.5 on 2026-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
