# Generated by Django 6.0.5 on 2026-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_verification_otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
